FROM node:18-alpine3.20 as build

WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn install

COPY . .
RUN yarn build

FROM node:18-alpine3.20

WORKDIR /app
RUN yarn global add http-server

COPY --from=build /app/build /app/build

EXPOSE 80
CMD ["http-server", "build", "-p", "80"]
