version: "2"

services:
  poke-ruby-js:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - nginx-net

networks:
  nginx-net:
