FROM node:18-alpine3.20 as build

WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install

COPY . .
RUN npm run build

FROM node:18-alpine3.20

WORKDIR /app
RUN npm install -g http-server

COPY --from=build /app/build /app/build

EXPOSE 80
CMD ["http-server", "build", "-p", "80"]
